# Generated by Django 2.0.5 on 2018-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка')),
            ],
        ),
    ]
